LL = __import__("01_linked_list")

my_LL = LL.LinkedList(10)

my_LL.insert(-1,7)
my_LL.print_list()
print("###")
my_LL.insert(0,12)
my_LL.print_list()
print("###")
my_LL.insert(1,3)
my_LL.print_list()
print("###")
my_LL.insert(3,9)
my_LL.print_list()
print("###")
my_LL.insert(7,8)
my_LL.print_list()
print("###")
my_LL.insert(2,7)
my_LL.print_list()
